# Generated by Django 4.2 on 2025-05-31 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(blank=True, max_length=250, null=True)),
                ('book_photo', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('author_photo', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_of_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('period_of_rent', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, choices=[('available', 'available'), ('rental', 'rental'), ('sold', 'sold')], max_length=50, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms_app.category')),
            ],
        ),
    ]
